# base image
FROM node:20-alpine

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY package.json .

RUN npm install

COPY . .

EXPOSE 8083
# start app
CMD ["npm", "run","preview"]

# CMD ["npm", "run","dev"]